# This is a basic workflow to help you get started with Actions

name: Artifact Upload

env:
  PROJECT_NAME: gha-101

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  upload-artifact:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo $PROJECT_NAME
          echo "PROJECT_VERSION=0.1" >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Upload an artifact
        uses: actions/upload-artifact@v4
        with:
          path: src/
          name: ${{ env.PROJECT_NAME }}-${{ env.PROJECT_VERSION }}-${{ github.run_id }}-artifact

