name: keyword-releaser

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: MykytaKostiuk/GHA-101-custom-action@main
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: 'FIXED'